# Generated by Django 3.1.6 on 2021-03-19 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210317_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readed_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
