# Generated by Django 3.1.6 on 2021-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.CharField(max_length=1000, verbose_name='Анонс')),
                ('date', models.DateTimeField(verbose_name='Дата Публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
