# Generated by Django 3.1.6 on 2021-03-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210324_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesForm',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
