# Generated by Django 3.1.6 on 2021-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photo', verbose_name='Аватарка автора'),
        ),
    ]
