# Generated by Django 3.1.6 on 2021-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_author_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author_photo',
        ),
    ]
